-- 코드를 입력하세요
WITH SELL AS(
    SELECT b.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, s.SALES_DATE, s.SALES, b.PRICE
    FROM BOOK b
    JOIN AUTHOR a ON b.AUTHOR_ID = a.AUTHOR_ID
    JOIN BOOK_SALES s ON b.BOOK_ID = s.BOOK_ID
    WHERE DATE_FORMAT(s.SALES_DATE, '%Y-%m-%d') LIKE '2022-01%'
)
SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(PRICE * SALES) AS TOTAL_SALES
FROM SELL
GROUP BY 1, 3
ORDER BY 1, 3 DESC;