WITH ROOT AS( -- 루트 아이템 필터링
    SELECT ITEM_ID
    FROM ITEM_TREE
    WHERE PARENT_ITEM_ID IS NULL
)

SELECT 
    r.ITEM_ID,
    i.ITEM_NAME
FROM ROOT r
JOIN ITEM_INFO i ON r.ITEM_ID = i.ITEM_ID
ORDER BY 1