WITH GEN1 AS( -- 1세대
    SELECT ID AS GEN1_ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
)

, GEN2 AS( -- 2세대
    SELECT e.ID AS GEN2_ID
    FROM ECOLI_DATA e
    JOIN GEN1 g1 ON e.PARENT_ID = g1.GEN1_ID
)

-- 3세대 조회
SELECT e.ID
FROM ECOLI_DATA e
JOIN GEN2 g2 ON e.PARENT_ID = g2.GEN2_ID
ORDER BY 1