-- 코드를 작성해주세요
WITH CHILD AS (
    SELECT PARENT_ID AS ID, COUNT(PARENT_ID) AS CNT
    FROM ECOLI_DATA
    GROUP BY 1
)
SELECT e.ID, IFNULL(c.CNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA e
LEFT JOIN CHILD c ON e.ID=c.ID
ORDER BY 1;