-- 코드를 입력하세요
WITH AVAILABLE AS(
    SELECT c.CAR_ID, c.CAR_TYPE, c.DAILY_FEE, 
        h.HISTORY_ID, h.START_DATE, h.END_DATE, 
        d.DURATION_TYPE, d.DISCOUNT_RATE,
        ROUND((c.DAILY_FEE * (100 - d.DISCOUNT_RATE) / 100) * 30) AS FEE
	FROM CAR_RENTAL_COMPANY_CAR c
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h ON c.CAR_ID = h.CAR_ID
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN d ON c.CAR_TYPE = d.CAR_TYPE
	WHERE c.CAR_ID NOT IN(
        SELECT CAR_ID
		FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
		WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-12-01'
		)
    AND c.CAR_TYPE IN ('세단', 'SUV')
    AND d.DURATION_TYPE LIKE '30%'
    GROUP BY 1
)
SELECT CAR_ID, CAR_TYPE, FEE
FROM AVAILABLE
WHERE FEE >= 500000 AND FEE < 2000000
ORDER BY 3 DESC, 2 ASC, 1 DESC;


