WITH RANK_SIZE AS (
    SELECT
        ID,
        SIZE_OF_COLONY,
        ROW_NUMBER() OVER (ORDER BY SIZE_OF_COLONY DESC) AS SIZERANK,
        COUNT(*) OVER () AS TOTAL_COUNT
    FROM ECOLI_DATA
)
SELECT
    ID,
    CASE
        WHEN (SIZERANK <= TOTAL_COUNT * 0.25) THEN 'CRITICAL'
        WHEN (SIZERANK <= TOTAL_COUNT * 0.50) THEN 'HIGH'
        WHEN (SIZERANK <= TOTAL_COUNT * 0.75) THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM RANK_SIZE
ORDER BY 1;
