WITH INS AS(
    SELECT ANIMAL_ID, ANIMAL_TYPE, NAME, SEX_UPON_INTAKE
    FROM ANIMAL_INS
    WHERE SEX_UPON_INTAKE LIKE 'I%'
)
SELECT o.ANIMAL_ID, o.ANIMAL_TYPE, o.NAME
FROM INS i
JOIN ANIMAL_OUTS o ON i.ANIMAL_ID=o.ANIMAL_ID
WHERE o.SEX_UPON_OUTCOME LIKE 'S%' 
OR o.SEX_UPON_OUTCOME LIKE 'N%' 
ORDER BY 1;