-- 코드를 입력하세요
SELECT YEAR(o.SALES_DATE) AS YEAR,
        MONTH(o.SALES_DATE) AS MONTH,
        u.GENDER,
        COUNT(DISTINCT u.USER_ID) AS USERS
FROM ONLINE_SALE o
LEFT JOIN USER_INFO u ON o.USER_ID = u.USER_ID
GROUP BY 1, 2, 3
HAVING u.GENDER IS NOT NULL
ORDER BY 1, 2, 3;