WITH duration AS( -- 자동자id별 총 대여기간 조회
    SELECT
        CAR_ID,
        HISTORY_ID,
        DATEDIFF(END_DATE, START_DATE)+1 AS DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
)

SELECT
    CAR_ID,
    ROUND(AVG(DURATION), 1) AS AVERAGE_DURATION
FROM duration
GROUP BY 1
HAVING AVG(DURATION) >= 7
ORDER BY 2 DESC, 1 DESC;