WITH ordering AS(
    SELECT
        ROUTE,
        ROUND(SUM(D_BETWEEN_DIST), 1) AS TOTAL_DISTANCE,
        ROUND(AVG(D_BETWEEN_DIST), 2) AS AVERAGE_DISTANCE
    FROM SUBWAY_DISTANCE
    GROUP BY 1
    ORDER BY 2 DESC
)

SELECT
    ROUTE,
    CONCAT(TOTAL_DISTANCE, 'km') AS TOTAL_DISTANCE,
    CONCAT(AVERAGE_DISTANCE, 'km') AS AVERAGE_DISTANCE
FROM ordering