-- 21년도에 가입한 회원 정보
WITH JOINERS AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)
-- 21년도에 가입한 회원들 중, 상품 구매 이력이 있는 회원의 구매 정보
, PURCHASED AS (
    SELECT USER_ID, YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH
    FROM ONLINE_SALE
    WHERE USER_ID IN (SELECT USER_ID FROM JOINERS)
    GROUP BY USER_ID, YEAR(SALES_DATE), MONTH(SALES_DATE)
)
SELECT 
    YEAR,
    MONTH,
    COUNT(DISTINCT USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT USER_ID) / (SELECT COUNT(*) FROM JOINERS), 1) AS PURCHASED_RATIO
FROM PURCHASED
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;
