-- 코드를 작성해주세요
WITH RECURSIVE GEN AS(
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT e.ID, e.PARENT_ID, g.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA e
    JOIN GEN g ON e.PARENT_ID = g.ID
)

SELECT COUNT(ID) AS COUNT, GENERATION
FROM GEN
WHERE ID NOT IN(
    SELECT DISTINCT PARENT_ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY 2
ORDER BY 2;