-- 코드를 입력하세요
WITH A AS(
    SELECT o.PRODUCT_ID, p.PRODUCT_NAME, p.PRICE, o.AMOUNT
    FROM FOOD_ORDER o
    LEFT JOIN FOOD_PRODUCT p ON o.PRODUCT_ID=p.PRODUCT_ID
    WHERE o.PRODUCE_DATE LIKE '2022-05%'
)
SELECT PRODUCT_ID, PRODUCT_NAME, SUM(PRICE * AMOUNT) AS TOTAL_SALES
FROM A
GROUP BY 1
ORDER BY 3 DESC, 1;