WITH TRUCKRENTAL AS(
    SELECT
        h.HISTORY_ID,
        h.CAR_ID,
        c.CAR_TYPE,
        c.DAILY_FEE,
        DATEDIFF(END_DATE, START_DATE) + 1 AS DURATION,
        CASE
            WHEN (DATEDIFF(END_DATE, START_DATE) + 1) >= 90 THEN '90일 이상'
            WHEN (DATEDIFF(END_DATE, START_DATE) + 1) >= 30 AND (DATEDIFF(END_DATE, START_DATE) + 1) < 90 THEN '30일 이상'
            WHEN (DATEDIFF(END_DATE, START_DATE) + 1) >= 7 AND (DATEDIFF(END_DATE, START_DATE) + 1) < 30 THEN '7일 이상'
            ELSE NULL
        END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
    JOIN CAR_RENTAL_COMPANY_CAR c ON h.CAR_ID = c.CAR_ID
    WHERE c.CAR_TYPE = '트럭'
)

, TRUCKPLAN AS(
    SELECT
        t.HISTORY_ID,
        t.CAR_ID,
        t.DAILY_FEE,
        t.DURATION,
        CASE
            WHEN t.DURATION_TYPE IS NULL THEN 0
            ELSE d.DISCOUNT_RATE
        END AS DISCOUNT_RATE
    FROM TRUCKRENTAL t
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN d ON t.CAR_TYPE = d.CAR_TYPE AND t.DURATION_TYPE = d.DURATION_TYPE
)

SELECT
    HISTORY_ID,
    ROUND(DAILY_FEE * (100-DISCOUNT_RATE)/100 * DURATION, 0) AS FEE
FROM TRUCKPLAN
ORDER BY 2 DESC, 1 DESC