-- 코드를 입력하세요
WITH JULY_ORDER AS( -- 7월 아이스크림 주문량 합산
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER_JULY
    FROM JULY
    GROUP BY FLAVOR
),
TOTAL AS( -- 상반기 + 7월 아이스크림 주문량 합산
    SELECT f.FLAVOR, (f.TOTAL_ORDER + j.TOTAL_ORDER_JULY) AS TOTAL_ORDER
    FROM FIRST_HALF f
    JOIN JULY_ORDER j ON f.FLAVOR=j.FLAVOR
    ORDER BY 2 DESC
    LIMIT 3 -- 상위 3개만 추출
)
SELECT FLAVOR
FROM TOTAL;