-- 코드를 입력하세요
WITH CS_APP AS(
    SELECT APNT_YMD, APNT_NO, PT_NO, MCDP_CD, MDDR_ID
    FROM APPOINTMENT
    WHERE APNT_YMD LIKE '2022-04-13%'
    AND MCDP_CD = 'CS'
    AND APNT_CNCL_YN = 'N'
)
SELECT c.APNT_NO, p.PT_NAME, p.PT_NO, c.MCDP_CD, d.DR_NAME, c.APNT_YMD
FROM CS_APP c
JOIN PATIENT p ON c.PT_NO = p.PT_NO
JOIN DOCTOR d ON c.MDDR_ID = d.DR_ID
ORDER BY c.APNT_YMD;