-- 코드를 입력하세요
WITH CNT AS (
    SELECT REVIEW_ID, 
            MEMBER_ID, 
            COUNT(REVIEW_ID) AS cnt
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY cnt DESC
    LIMIT 1
)
SELECT m.MEMBER_NAME, r.REVIEW_TEXT, DATE_FORMAT(r.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE m
JOIN CNT c ON m.MEMBER_ID=c.MEMBER_ID
JOIN REST_REVIEW r ON m.MEMBER_ID=r.MEMBER_ID
ORDER BY 3, 2;