WITH RARE AS(
    SELECT
        t.ITEM_ID AS UPGRADE_ITEM_ID
    FROM ITEM_TREE t
    JOIN (
        SELECT ITEM_ID AS PARENT_ITEM_ID
        FROM ITEM_INFO
        WHERE RARITY = 'RARE'
    ) p ON t.PARENT_ITEM_ID = p.PARENT_ITEM_ID   
)

SELECT
    i.ITEM_ID,
    i.ITEM_NAME,
    i.RARITY
FROM ITEM_INFO i
JOIN RARE r ON i.ITEM_ID = r.UPGRADE_ITEM_ID
ORDER BY 1 DESC;