WITH YEARMAX AS( -- 연도별 가장 큰 대장균 크기 추출
    SELECT
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAXSIZE_OF_YEAR
    FROM ECOLI_DATA
    GROUP BY 1
)

SELECT
    e.YEAR,
    (m.MAXSIZE_OF_YEAR - e.SIZE_OF_COLONY) AS YEAR_DEV,
    e.ID
FROM (
    SELECT
        ID,
        SIZE_OF_COLONY,
        YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA
) e
JOIN YEARMAX m ON e.YEAR = m.YEAR
ORDER BY 1, 2