-- 코드를 작성해주세요
SELECT ID, FISH_NAME, f.LENGTH AS LENGTH
FROM FISH_INFO f
JOIN FISH_NAME_INFO fn ON f.FISH_TYPE = fn.FISH_TYPE
WHERE f.FISH_TYPE IN 
(
    SELECT FISH_TYPE
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    HAVING LENGTH = MAX(LENGTH)
)
ORDER BY ID