WITH ICECREAM_JOIN AS(
    SELECT 
        f.SHIPMENT_ID,
        f.FLAVOR,    
        i.INGREDIENT_TYPE,
        f.TOTAL_ORDER
    FROM FIRST_HALF f
    INNER JOIN ICECREAM_INFO i ON f.FLAVOR = i.FLAVOR
)

SELECT
    INGREDIENT_TYPE,
    SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM ICECREAM_JOIN
GROUP BY 1
ORDER BY 2