-- 코드를 작성해주세요
SELECT em.DEPT_ID,
    de.DEPT_NAME_EN,
    ROUND(AVG(em.SAL), 0) AS AVG_SAL
FROM HR_EMPLOYEES em
JOIN HR_DEPARTMENT de ON em.DEPT_ID = de.DEPT_ID
GROUP BY 1 -- 부서별로 묶음
ORDER BY AVG_SAL DESC;