-- 코드를 입력하세요
WITH TEMP AS(
	SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
    HAVING CATEGORY IN ('과자', '국', '김치', '식용유')
)
SELECT T.CATEGORY, T.MAX_PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT F
INNER JOIN TEMP T
ON F.CATEGORY = T.CATEGORY AND F.PRICE = T.MAX_PRICE
ORDER BY 2 DESC;